# Generated by Django 2.2.4 on 2020-08-12 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_employee_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='active',
        ),
    ]
